title: "[Idea] "
labels:
  - idea
body:
  - type: markdown
    attributes:
      value: |
        ## Share Your Idea

        Have an idea for improving iOS Simulator MCP? We'd love to hear it!

  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: Describe your idea
      placeholder: I think it would be great if...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it Solves
      description: What problem does this idea solve?
      placeholder: This would help with...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives?
      placeholder: I also thought about...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples?
