"""Application-wide constants for the iOS Simulator MCP server."""

SIMULATOR_BUNDLE_ID = "com.apple.iphonesimulator"
DEFAULT_GRID_STEP = 40
DEFAULT_MAX_DEPTH = 60
DEFAULT_MAX_GRID_POINTS = 400
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_DEVICE_ID_ENV = "IOS_SIM_DEVICE_ID"
DEFAULT_ACTIVATE_APP_ENV = "IOS_SIM_ACTIVATE_APP"
