"""Application-wide constants for the iOS Simulator MCP server."""

SIMULATOR_BUNDLE_ID = "com.apple.iphonesimulator"
DEFAULT_GRID_STEP = 40
DEFAULT_MAX_DEPTH = 60
DEFAULT_MAX_GRID_POINTS = 400
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_DEVICE_ID_ENV = "IOS_SIM_DEVICE_ID"
DEFAULT_ACTIVATE_APP_ENV = "IOS_SIM_ACTIVATE_APP"
DEFAULT_STRICT_ACTIONS_ENV = "IOS_SIM_STRICT_ACTIONS"
DEFAULT_ACCESSIBILITY_TRUST_CACHE_TTL_SECONDS = 2.0
DEFAULT_SIMCTL_TIMEOUT_SECONDS = 12.0
DEFAULT_SIMCTL_RETRY_COUNT = 1
DEFAULT_SIMCTL_RETRY_BACKOFF_SECONDS = 0.15
DEFAULT_BOOTED_DEVICE_CACHE_TTL_SECONDS = 0.4
